myApp/urls.py
from django.conf.urls import url
from . import views


app_name = 'myApp'

urlpatterns = [

        url(r'^$', views.renderHome, name='index'), 
        url(r'^list$', views.getList, name='list'), 
        url(r'^add$', views.getAdd, name='add'), 
         
 ]      

seedStarApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('myApp.urls', namespace='seed')),
]

myApp/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class UserAccount(models.Model):
    name   = models.CharField(max_length = 70)
    email = models.EmailField(max_length = 50, )
    

    def __str__(self):
        return self.name

    class Meta():
        verbose_name_plural  = 'UserAccount'

myApp/forms.py
from django import forms
from .models import UserAccount

class AddForm(forms.ModelForm):
    
    name = forms.CharField(max_length = 120, help_text = '',  widget = forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'Your Name', 'required': 'required'}))
    email = forms.EmailField(max_length = 120,  help_text = '',  widget = forms.EmailInput(attrs = {'class': 'form-control', 'placeholder': 'email@example.com', 'required': 'required'}))
   
    class Meta:
        model = UserAccount
        fields = ('name', 'email',)

myApp/views.py
from django.shortcuts import render, redirect
#from django.http import HttpResponse, JsonResponse
from myApp.forms import AddForm
from myApp.models import UserAccount
from django.contrib import messages

# Create your views here.

def renderHome(request):
    context = {}
    return render(request, 'myApp/index.html', context)


def getList(request):
    context = {
        'records': UserAccount.objects.all()
    }
    return render(request, 'myApp/list.html', context)


def getAdd(request):
    add_form = AddForm()
    context = {
        'add_form': add_form
    }
    if request.method == 'POST':
        user = None
        add_form = AddForm(data = request.POST)
        rp = request.POST
        
        if add_form.is_valid():   
            user = UserAccount.objects.create(name = rp['name'], email = rp['email'], )
            user.save()
            if user:
                messages.success(request, 'Your details have been saved')
            else:
                messages.warning(request, 'something went wrong acount not created!! please try again!')
        else:
            context['add_form'] = AddForm(data = request.POST)
    return render(request, 'myApp/add.html', context)

myApp/templates/myApp/add.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
  <title>MyApp</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container">
    <h1>ADD RECORDS</h1><br>
  <div class="row">
          
  
    <form class="col-md-4" method= "post" action= "{% url 'seed:add' %}">
       
      {% csrf_token %}
        {{ add_form.as_p}}
        {{add_form.as_errors}}
        <input class="btn btn-primary" type="submit" name="submit" value="submit">

    </form>
  
    </div>
    <br><br>
    <p><a href="{% url 'seed:list' %}">LIST</a></p>
    <p><a href="{% url 'seed:index' %}">HOME</a></p>
</div>
</body>
</html>
 

myApp/templates/myApp/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
  <title>MyApp</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container">
  <div class="row">
  
  
    <h1>WELCOME TO MY APP</h1><br>

    <p><a href="{% url 'seed:add' %}">ADD</a></p>
    <p><a href="{% url 'seed:list' %}">LIST</a></p>
  
    </div>
</div>
</body>
</html>

myApp/templates/myApp/list.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
  <title>MyApp</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container">
  <div class="row">
  
  
    <h1>LIST OF RECORDS</h1><br>

    {% for record in records %}
		<div class="col-md-12">
		
			<div class="">
				NAME: <strong class="text-primary">{{ record.name|capfirst }}</strong>
			</div>
			<div class="">
				EMAIL: <strong class="text-primary">{{ record.email }}</strong>
			</div><br>
		</div>


	{% empty %}
		<p>Sorry you don't have any record in the list yet</p>
	{% endfor %}
  
    </div>
    <br><br>
    <p><a href="{% url 'seed:add' %}">ADD</a></p>
    <p><a href="{% url 'seed:index' %}">HOME</a></p>
</div>
</body>
</html>